# 应用配置
app:
  addr: "0.0.0.0:8080"  # 应用监听地址，格式为 IP:PORT，例如 ":8080"

# JWT 配置
jwt:
  secretKey: "your-secret-key"  # JWT 加密秘钥
  timeout: 2592000          # 一个月过期一次

# 数据库配置
db:
  dsn: "root:chenhaoqi318912-pw@tcp(60.205.12.92:3306)/muxiAuditor?charset=utf8mb4&parseTime=True&loc=Local"

# 缓存配置
cache:
  addr: "60.205.12.92:6379"  # Redis 地址，格式为 IP:PORT，例如 "127.0.0.1:6379"
  password: "chenhaoqi318912" # Redis 密码（如果没有设置密码，可留空）
  db: 0 #默认数据库

# OAuth 配置
oauth:
  addr: "http://pass.muxi-tech.xyz/auth/api" # OAuth 服务地址
  clientId: "dc0c99b7-4e9e-4e61-8344-258141fd673d"   # OAuth Client ID
  clientSecret: "a65b9f92-055c-40fb-a254-153da77ed142" # OAuth Client Secret

# 日志配置
log:
  path: "./logs/app.log"  # 日志文件路径
  maxSize: 100           # 单个日志文件的最大大小（MB）
  maxBackups: 7          # 保留旧日志文件的最大数量
  maxAge: 30             # 日志文件保留天数
  compress: 1             # 是否压缩旧日志文件（1 表示压缩，0 表示不压缩）

# Prometheus 配置
prometheus:
  namespace: "muxiAuditor" # Prometheus 命名空间，通常为项目名称

  routerCounter:
    name: "http_requests_total"  # 路由请求总数指标名称
    help: "Total number of HTTP requests" # 指标说明

  activeConnections:
    name: "active_connections"  # 活跃连接指标名称
    help: "Number of active connections per route" # 指标说明

  durationTime:
    name: "http_request_duration_seconds"  # 请求时长直方图名称
    help: "Histogram of response times for HTTP requests" # 指标说明

# 中间件配置
middleware:
  allowedOrigins:
    - "*"  # 允许跨域访问的来源地址，例如前端开发服务器地址
    - "https://auditor.muxixyz.com"     # 生产环境中允许的域名
QiNiuYun:
  AccessKey: "0bNiwJGpdwmvvuVAzLDjM6gnxj9MiwmSagVpIW81" #七牛云的公钥
  SecretKey: "zHA9w8PoSfL6D4dvWNwU2GF4XHUn9MalynbANE3_" #七牛云的私钥
  Bucket : "muxi-miniproject" #所创建七牛云对象存储的名称
  Domain : "mini-project.muxixyz.com" #对象存储所绑定的七牛云的域名