# 应用配置
app:
  addr: ":8080"  # 应用监听地址，格式为 IP:PORT，例如 ":8080"

# JWT 配置
jwt:
  secretKey: "your-secret-key"  # JWT 加密秘钥
  timeout: 2592000          # 一个月过期一次

# 数据库配置
db:
  dsn: "root:123456@tcp(localhost:3306)/muxiAuditor?charset=utf8mb4&parseTime=True&loc=Local"

# 缓存配置
cache:
  addr: "127.0.0.1:6379"  # Redis 地址，格式为 IP:PORT，例如 "127.0.0.1:6379"
  password: "" # Redis 密码（如果没有设置密码，可留空）

# OAuth 配置
oauth:
  addr: "http://127.0.0.1:8081" # OAuth 服务地址
  clientId: "your-client-id"   # OAuth Client ID
  clientSecret: "your-client-secret" # OAuth Client Secret

# 日志配置
log:
  path: "./logs/app.log"  # 日志文件路径
  maxSize: 100           # 单个日志文件的最大大小（MB）
  maxBackups: 7          # 保留旧日志文件的最大数量
  maxAge: 30             # 日志文件保留天数
  compress: 1             # 是否压缩旧日志文件（1 表示压缩，0 表示不压缩）

# Prometheus 配置
prometheus:
  namespace: "muxiAuditor" # Prometheus 命名空间，通常为项目名称

  routerCounter:
    name: "http_requests_total"  # 路由请求总数指标名称
    help: "Total number of HTTP requests" # 指标说明

  activeConnections:
    name: "active_connections"  # 活跃连接指标名称
    help: "Number of active connections per route" # 指标说明

  durationTime:
    name: "http_request_duration_seconds"  # 请求时长直方图名称
    help: "Histogram of response times for HTTP requests" # 指标说明

# 中间件配置
middleware:
  allowedOrigins:
    - "http://localhost:3000"  # 允许跨域访问的来源地址，例如前端开发服务器地址
    - "https://auditor.muxixyz.com"     # 生产环境中允许的域名
QiNiuYun:
  AccessKey: "access-key" #七牛云的公钥
  SecretKey: "secret-key" #七牛云的私钥
  Bucket : "muxi-mini" #所创建七牛云对象存储的名称
  Domain : "http://127.0.0.1:8080" #对象存储所绑定的七牛云的域名